/**
 * @file RA Laboratory Concepts
 * @description Typed concepts for serologic, inflammatory, and safety monitoring tests in Rheumatoid Arthritis.
 */

export enum RaLaboratoryTestCategory {
  RHEUMATOID_FACTOR = "RHEUMATOID_FACTOR",
  ANTI_CITRULLINATED_PROTEIN_ANTIBODY = "ANTI_CITRULLINATED_PROTEIN_ANTIBODY", // ACPA / anti-CCP
  ERYTHROCYTE_SEDIMENTATION_RATE = "ERYTHROCYTE_SEDIMENTATION_RATE", // ESR
  C_REACTIVE_PROTEIN = "C_REACTIVE_PROTEIN", // CRP
  COMPLETE_BLOOD_COUNT = "COMPLETE_BLOOD_COUNT", // CBC
  LIVER_FUNCTION_TEST = "LIVER_FUNCTION_TEST", // LFT / Transaminases
  SERUM_CREATININE = "SERUM_CREATININE",
  TUBERCULOSIS_SCREENING = "TUBERCULOSIS_SCREENING", // IGRA (QuantiFERON/T-SPOT) or PPD
  VIRAL_HEPATITIS_SCREENING = "VIRAL_HEPATITIS_SCREENING", // HBV / HCV
  OTHER_LABORATORY = "OTHER_LABORATORY",
}
