/**
 * @file RA Manifestation Concepts (Articular & Extra-Articular)
 * @description Candidate anatomical manifestations and structural damage classifications pending specialist sign-off.
 */

export enum RaArticularManifestationKind {
  PERIPHERAL_SYNOVITIS = "PERIPHERAL_SYNOVITIS",
  JOINT_EROSION = "JOINT_EROSION",
  JOINT_SPACE_NARROWING = "JOINT_SPACE_NARROWING",
  ULNAR_DEVIATION = "ULNAR_DEVIATION",
  SWAN_NECK_DEFORMITY = "SWAN_NECK_DEFORMITY",
  BOUTONNIERE_DEFORMITY = "BOUTONNIERE_DEFORMITY",
  RHEUMATOID_SUBLUXATION = "RHEUMATOID_SUBLUXATION",
}

export enum RaExtraArticularManifestationKind {
  RHEUMATOID_NODULES = "RHEUMATOID_NODULES",
  INTERSTITIAL_LUNG_DISEASE_RA_ILD = "INTERSTITIAL_LUNG_DISEASE_RA_ILD",
  RHEUMATOID_VASCULITIS = "RHEUMATOID_VASCULITIS",
  SECONDARY_SJOGRENS_SYNDROME = "SECONDARY_SJOGRENS_SYNDROME",
  SCLERITIS_EPISCLERITIS = "SCLERITIS_EPISCLERITIS",
  PLEURAL_EFFUSION = "PLEURAL_EFFUSION",
  PERICARDITIS = "PERICARDITIS",
  FELTY_SYNDROME = "FELTY_SYNDROME",
  OTHER_EXTRA_ARTICULAR = "OTHER_EXTRA_ARTICULAR",
}
